# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

remote_theme: daviddarnes/alembic

# 3. Gem settings
paginate: 12 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Rejoice # jekyll-seo-tag > Owners twitter username
author: Rejoice # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Rejoice # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Rejoice
    - https://www.facebook.com/Rejoice
    - https://www.linkedin.com/in/Rejoice
    - https://github.com/Rejoice
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Kolkata # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Learn Guitar Chords" # The post list page content
#    feature_text: |
#      Welcome to the blog
#    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Rejoice" # Site name or title, also used in jekyll-seo-tag
#logo: "/assets/logos/logo.png" # Site logo, also used in jekyll-seo-tag
logo: "/assets/logos/logo.png" # Site logo, also used in jekyll-seo-tag
description: "the blade of grass | Learn Guitar" # Site description and default description, also used in jekyll-seo-tag
url: "https://thebladeofgrass.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/Rejoice/alembic"
email: "hello@thebladeofgrass.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
google_analytics: 'UA-159115192-1'
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon.jpg'
  32: '/assets/logos/favicon.jpg'
  96: '/assets/logos/favicon.jpg'
  120: '/assets/logos/favicon.jpg'
  144: '/assets/logos/favicon.jpg'
  180: '/assets/logos/favicon.jpg'
  512: '/assets/logos/favicon.jpg'
  1024: '/assets/logos/favicon.jpg'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Topics
  url: /categories/
- title: Search
  url: /search/
#- title: Fork Alembic
#  url: https://github.com/Rejoice/alembic

navigation_footer:
- title: Rejoice
  url: https://thebladeofgrass.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/Rejoice
  LinkedIn: https://www.linkedin.com/in/Rejoice
  GitHub: https://github.com/Rejoice
  link: https://thebladeofgrass.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
